### ISSUE TITLE
HUD Disappears 

### ISSUE THREAD

**Issue by Caaine** [Prefix/timer-for-csgo#1]
can you fix it pls? :dancer: 

L 04/12/2016 - 10:30:31: Info (map "bhop_eazy_v2") (file "errors_20160412.log")
L 04/12/2016 - 10:30:31: [SM] Native "GetArrayArray" reported: Invalid index 9 (count: 1)
L 04/12/2016 - 10:30:31: [SM] Displaying call stack trace for plugin "timer-worldrecord.smx":
L 04/12/2016 - 10:30:31: [SM]   [0]  Line 1840, G:\csgo\plugin zips\Timer\addons\sourcemod\scripting\timer-worldrecord.sp::Native_GetBestRound()
L 04/12/2016 - 10:30:31: [SM] Native "Timer_GetBestRound" reported: Error encountered while processing a dynamic native
L 04/12/2016 - 10:30:31: [SM] Displaying call stack trace for plugin "timer-hud_csgo.smx":
L 04/12/2016 - 10:30:31: [SM]   [0]  Line 1442, G:\csgo\plugin zips\Timer\addons\sourcemod\scripting\timer-hud_csgo.sp::UpdateHUD_CSGO()
L 04/12/2016 - 10:30:31: [SM]   [1]  Line 1322, G:\csgo\plugin zips\Timer\addons\sourcemod\scripting\timer-hud_csgo.sp::HUDTimer_CSGO()
L 04/12/2016 - 10:47:23: Error log file session closed.

**Comment by Prefix** [comment]
Hello. Try newest version I had attached :)

**Comment by Prefix** [comment]
If you still have the same problem make new issue.
